### ISSUE TITLE
Indication of student status on student list page for advisors/dept chairs

### ISSUE THREAD

**Issue by drewvolz** [hawkrives/gobbldygook#119]
An at-a-glance status at who is on track to graduate. I believe you said we have to information, we just need to render it.

**Comment by hawkrives** [comment]
So, it turns out that we do have the information, but it's behind a promise, which means that we'd need to store local state in `<StudentPicker/>`…

I mean, that's how `<StudentSummary/>` works already, but I'm (kinda) trying to avoid adding more local state — I want to switch to [redux] at some point, which will help facilitate this sort of global state management.

Then the global state will be able to store things like – search queries! and sorting options! and the current student's id! and the results of promises, rather than just the promises!

Anyway.

[redux]: http://rackt.github.io/redux/

**Comment by hawkrives** [comment]
<img width="76" alt="screen shot 2016-01-23 at 9 23 41 am" src="https://cloud.githubusercontent.com/assets/464441/12530901/fb77b04e-c1b2-11e5-9867-2674b5937e86.png">

Done!
